/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.controladorHotel;
import Modelo.*;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author HP
 */
public class jm extends javax.swing.JPanel {
    
    controladorHotel Hotel;

    /**
     * Creates new form jm
     */
    public jm() {
        initComponents();
        llenarCombos();
        Hotel = new controladorHotel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        pnlAdminClientes = new javax.swing.JPanel();
        lblTituloAdminClientes = new javax.swing.JLabel();
        lblDocumentoCliente = new javax.swing.JLabel();
        txtDocumentoCliente = new javax.swing.JTextField();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblCorreoCliente = new javax.swing.JLabel();
        txtCorreoCliente = new javax.swing.JTextField();
        lblTelefonoCliente = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        lblFechaNacimientoCliente = new javax.swing.JLabel();
        lblDiaNacimientoCliente = new javax.swing.JLabel();
        lblMesNacimientoCliente = new javax.swing.JLabel();
        lblAnioNacimientoCliente = new javax.swing.JLabel();
        cbxDiaNacimientoCliente = new javax.swing.JComboBox<>();
        cbxMesNacimientoCliente = new javax.swing.JComboBox<>();
        cbxAñoNacimiento = new javax.swing.JComboBox<>();
        lblEstaturaCliente = new javax.swing.JLabel();
        txtEstaturaCliente = new javax.swing.JTextField();
        lblTipoCliente = new javax.swing.JLabel();
        cbxTipoCliente = new javax.swing.JComboBox<>();
        btnCrearCliente = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblTipoHabitacion = new javax.swing.JLabel();
        lblNumeroH = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNumeroH = new javax.swing.JTextField();
        jcbTipoHabitacion = new javax.swing.JComboBox<>();
        bCrear = new javax.swing.JButton();
        bActualizar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        chbDispo = new javax.swing.JCheckBox();
        chbOcu = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        lblCodigoRe = new javax.swing.JLabel();
        lblDoc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNHabitacion = new javax.swing.JLabel();
        lblTHabitacion = new javax.swing.JLabel();
        lblFechaIN = new javax.swing.JLabel();
        lblFechaSA = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblAño = new javax.swing.JLabel();
        jcbDiaIngreso = new javax.swing.JComboBox<>();
        jcbAñoIngreso = new javax.swing.JComboBox<>();
        jcbMesIngreso = new javax.swing.JComboBox<>();
        jcbDiaSalida = new javax.swing.JComboBox<>();
        jcbAñoSalida = new javax.swing.JComboBox<>();
        jcbMesSalida = new javax.swing.JComboBox<>();
        lblCantidadNoches = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDoc = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCodigoRe = new javax.swing.JTextField();
        jcbTHabitacion = new javax.swing.JComboBox<>();
        txtNHabitacion = new javax.swing.JTextField();
        txtCantidadNoches = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbCrear = new javax.swing.JButton();
        btnCalcularTotal = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Hotel U. Caldas");

        lblTituloAdminClientes.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTituloAdminClientes.setText("Administrar Huespedes");

        lblDocumentoCliente.setText("Documento");

        lblNombreCliente.setText("Nombre");

        lblCorreoCliente.setText("Correo");

        lblTelefonoCliente.setText("Teléfono");

        lblFechaNacimientoCliente.setText("Fecha Nacimiento");

        lblDiaNacimientoCliente.setText("Dia");

        lblMesNacimientoCliente.setText("Mes");

        lblAnioNacimientoCliente.setText("Año");

        cbxDiaNacimientoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDiaNacimientoClienteActionPerformed(evt);
            }
        });

        lblEstaturaCliente.setText("Estatura");

        lblTipoCliente.setText("Tipo de Huesped");

        cbxTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona Natural", "Persona Jurídica" }));

        btnCrearCliente.setText("Crear");
        btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClienteActionPerformed(evt);
            }
        });

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminClientesLayout = new javax.swing.GroupLayout(pnlAdminClientes);
        pnlAdminClientes.setLayout(pnlAdminClientesLayout);
        pnlAdminClientesLayout.setHorizontalGroup(
            pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminClientesLayout.createSequentialGroup()
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminClientesLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblTipoCliente)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTipoCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlAdminClientesLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombreCliente)
                            .addComponent(lblDocumentoCliente)
                            .addComponent(lblFechaNacimientoCliente)
                            .addComponent(lblEstaturaCliente)
                            .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCorreoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTelefonoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDocumentoCliente)
                            .addComponent(txtNombreCliente)
                            .addComponent(txtCorreoCliente)
                            .addComponent(txtTelefonoCliente)
                            .addGroup(pnlAdminClientesLayout.createSequentialGroup()
                                .addComponent(cbxDiaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxMesNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxAñoNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 82, Short.MAX_VALUE))
                            .addComponent(txtEstaturaCliente)))
                    .addGroup(pnlAdminClientesLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(lblDiaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(lblMesNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(lblAnioNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminClientesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTituloAdminClientes)
                .addGap(257, 257, 257))
        );
        pnlAdminClientesLayout.setVerticalGroup(
            pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAdminClientes)
                .addGap(53, 53, 53)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumentoCliente)
                    .addComponent(txtDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCliente)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoCliente)
                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoCliente)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addGap(28, 28, 28)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaNacimientoCliente)
                    .addComponent(lblMesNacimientoCliente)
                    .addComponent(lblAnioNacimientoCliente))
                .addGap(11, 11, 11)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimientoCliente)
                    .addComponent(cbxDiaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMesNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAñoNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCliente))
                .addGap(27, 27, 27)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstaturaCliente)
                    .addComponent(txtEstaturaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoCliente)
                    .addComponent(cbxTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlAdminClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlAdminClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Huespedes", jPanel2);

        lblTipoHabitacion.setText("Tipo de habitacion");

        lblNumeroH.setText("N° Habitacion");

        lblEstado.setText("Estado");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Gestionar Habitaciones");

        txtNumeroH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroHActionPerformed(evt);
            }
        });

        jcbTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habitación Sencilla", "Habitación Doble", "Suite" }));

        bCrear.setText("Crear");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        chbDispo.setText("Disponible");
        chbDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbDispoActionPerformed(evt);
            }
        });

        chbOcu.setText("Ocupado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(bBuscar)
                .addGap(18, 18, 18)
                .addComponent(bCrear)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(bActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(bEliminar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNumeroH, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)))
                .addGap(0, 206, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNumeroH)
                                    .addComponent(lblTipoHabitacion)
                                    .addComponent(chbDispo))
                                .addGap(54, 54, 54)
                                .addComponent(chbOcu)))
                        .addGap(251, 251, 251))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblEstado)
                        .addGap(366, 366, 366))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addGap(105, 105, 105)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoHabitacion))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroH)
                    .addComponent(txtNumeroH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(lblEstado)
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbDispo)
                    .addComponent(chbOcu))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBuscar)
                    .addComponent(bCrear)
                    .addComponent(bActualizar)
                    .addComponent(bEliminar))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Gestionar Habitaciones", jPanel4);

        lblCodigoRe.setText("Código Reserva");

        lblDoc.setText("Documento");

        jLabel3.setText("Nombre ");

        lblNHabitacion.setText("N° Habitacion");

        lblTHabitacion.setText("Tipo de Habiracion");

        lblFechaIN.setText("Fecha de ingreso");

        lblFechaSA.setText("Fecha de salida");

        lblDia.setText("Dia");

        lblMes.setText("Mes");

        lblAño.setText("Año");

        jcbAñoIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAñoIngresoActionPerformed(evt);
            }
        });

        lblCantidadNoches.setText("Cantidad de noches");

        lblValorTotal.setText("Valor total");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Gestionar reservas");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Datos Cliente");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Datos Reserva");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtCodigoRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoReActionPerformed(evt);
            }
        });

        jcbTHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habitación Sencilla", "Habitación Doble", "Suite" }));

        txtValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorTotalActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbCrear.setText("Crear");
        jbCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearActionPerformed(evt);
            }
        });

        btnCalcularTotal.setText("Calcular");
        btnCalcularTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDoc)
                            .addComponent(jLabel3)
                            .addComponent(lblCodigoRe))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDoc)
                            .addComponent(txtNombre)
                            .addComponent(txtCodigoRe, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaIN)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblFechaSA)))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jcbDiaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbMesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbAñoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jcbDiaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbMesIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbAñoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblDia)
                                    .addGap(58, 58, 58)
                                    .addComponent(lblMes)
                                    .addGap(64, 64, 64)
                                    .addComponent(lblAño)
                                    .addGap(36, 36, 36))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(lblNHabitacion))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(lblTHabitacion)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jcbTHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtNHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCantidadNoches))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCantidadNoches, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(txtValorTotal))
                                .addGap(86, 86, 86)
                                .addComponent(btnCalcularTotal))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(108, 108, 108))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoc)
                            .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jbBuscar)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoRe)
                    .addComponent(txtCodigoRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTHabitacion)
                    .addComponent(jcbTHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCrear))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNHabitacion)
                    .addComponent(txtNHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDia)
                            .addComponent(lblMes)
                            .addComponent(lblAño)
                            .addComponent(jbEliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaIN)
                            .addComponent(jcbDiaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbMesIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbAñoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaSA)
                            .addComponent(jcbDiaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbMesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbAñoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidadNoches)
                            .addComponent(txtCantidadNoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorTotal)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcularTotal)
                        .addGap(42, 42, 42))))
        );

        jTabbedPane2.addTab("Gestionar reservas", jPanel3);
        jTabbedPane2.addTab("", jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTotalActionPerformed
        // TODO add your handling code here:
        calcularTotal();
    }//GEN-LAST:event_btnCalcularTotalActionPerformed

    private void jbCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearActionPerformed
        // TODO add your handling code here:
        crearReserva();
    }//GEN-LAST:event_jbCrearActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        eliminarReserva();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        buscarReserva();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void txtValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorTotalActionPerformed

    private void txtCodigoReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoReActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoReActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jcbAñoIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAñoIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAñoIngresoActionPerformed

    private void chbDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbDispoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbDispoActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        eliminarHabitacion();
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        buscarHabitacion();
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        // TODO add your handling code here:
        actualizarHabitacion();
    }//GEN-LAST:event_bActualizarActionPerformed

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        // TODO add your handling code here:
        crearHabitacion();
    }//GEN-LAST:event_bCrearActionPerformed

    private void txtNumeroHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroHActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:
        EliminarHuesped();
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        buscarHuesped();
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
        // TODO add your handling code here:
        crearHuesped();
    }//GEN-LAST:event_btnCrearClienteActionPerformed

    private void cbxDiaNacimientoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDiaNacimientoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDiaNacimientoClienteActionPerformed

                                           
    
public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {

            javax.swing.JFrame ventana = new javax.swing.JFrame();

            ventana.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            ventana.setContentPane(new jm());
            ventana.pack();
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCalcularTotal;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JComboBox<String> cbxAñoNacimiento;
    private javax.swing.JComboBox<String> cbxDiaNacimientoCliente;
    private javax.swing.JComboBox<String> cbxMesNacimientoCliente;
    private javax.swing.JComboBox<String> cbxTipoCliente;
    private javax.swing.JCheckBox chbDispo;
    private javax.swing.JCheckBox chbOcu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCrear;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JComboBox<String> jcbAñoIngreso;
    private javax.swing.JComboBox<String> jcbAñoSalida;
    private javax.swing.JComboBox<String> jcbDiaIngreso;
    private javax.swing.JComboBox<String> jcbDiaSalida;
    private javax.swing.JComboBox<String> jcbMesIngreso;
    private javax.swing.JComboBox<String> jcbMesSalida;
    private javax.swing.JComboBox<String> jcbTHabitacion;
    private javax.swing.JComboBox<String> jcbTipoHabitacion;
    private javax.swing.JLabel lblAnioNacimientoCliente;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblCantidadNoches;
    private javax.swing.JLabel lblCodigoRe;
    private javax.swing.JLabel lblCorreoCliente;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblDiaNacimientoCliente;
    private javax.swing.JLabel lblDoc;
    private javax.swing.JLabel lblDocumentoCliente;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstaturaCliente;
    private javax.swing.JLabel lblFechaIN;
    private javax.swing.JLabel lblFechaNacimientoCliente;
    private javax.swing.JLabel lblFechaSA;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblMesNacimientoCliente;
    private javax.swing.JLabel lblNHabitacion;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNumeroH;
    private javax.swing.JLabel lblTHabitacion;
    private javax.swing.JLabel lblTelefonoCliente;
    private javax.swing.JLabel lblTipoCliente;
    private javax.swing.JLabel lblTipoHabitacion;
    private javax.swing.JLabel lblTituloAdminClientes;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel pnlAdminClientes;
    private javax.swing.JTextField txtCantidadNoches;
    private javax.swing.JTextField txtCodigoRe;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtDoc;
    private javax.swing.JTextField txtDocumentoCliente;
    private javax.swing.JTextField txtEstaturaCliente;
    private javax.swing.JTextField txtNHabitacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumeroH;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables

private void llenarCombos() {
        for (int i = 31; i >= 1; i--) {
            cbxDiaNacimientoCliente.addItem(i + "");
            jcbDiaIngreso.addItem(i + "");
            jcbDiaSalida.addItem(i + "");
        }
        for (int i = 12; i >= 1; i--) {
            cbxMesNacimientoCliente.addItem(i + "");
            jcbMesSalida.addItem(i + "");
            jcbMesIngreso.addItem(i + "");
        }
        for (int i = LocalDate.now().getYear(); i >= 1940; i--) {
            cbxAñoNacimiento.addItem(i + "");
            jcbAñoIngreso.addItem(i + "");
            jcbAñoSalida.addItem(i + "");
        }
}

public boolean validarCamposHuesped() {
    if (txtDocumentoCliente.getText().isBlank()) {
        JOptionPane.showMessageDialog(this, "El documento es obligatorio");
        return false;
    }
    if (txtNombreCliente.getText().isBlank()) {
        JOptionPane.showMessageDialog(this, "El nombre es obligatorio");
        return false;
    }
    if (txtCorreoCliente.getText().isBlank()) {
        JOptionPane.showMessageDialog(this, "El correo es obligatorio");
        return false;
    }
    if (txtTelefonoCliente.getText().isBlank()) {
        JOptionPane.showMessageDialog(this, "El teléfono es obligatorio");
        return false;
    }
    if (txtEstaturaCliente.getText().isBlank()) {
        JOptionPane.showMessageDialog(this, "La estatura es obligatoria");
        return false;
    }
    return true;
}



private void limpiarCamposHuesped() {
    txtDocumentoCliente.setText("");
    txtNombreCliente.setText("");
    txtCorreoCliente.setText("");
    txtTelefonoCliente.setText("");
    txtEstaturaCliente.setText("");
    cbxTipoCliente.setSelectedIndex(0);
    cbxDiaNacimientoCliente.setSelectedIndex(0);
    cbxMesNacimientoCliente.setSelectedIndex(0);
    cbxAñoNacimiento.setSelectedIndex(0);
}

private void crearHuesped() {
    if (validarCamposHuesped()) {
        String documento = txtDocumentoCliente.getText();
        String nombre = txtNombreCliente.getText();
        String correo = txtCorreoCliente.getText();
        String telefono = txtTelefonoCliente.getText();
        int dia = Integer.parseInt(cbxDiaNacimientoCliente.getSelectedItem().toString());
        int mes = Integer.parseInt(cbxMesNacimientoCliente.getSelectedItem().toString());
        int anio = Integer.parseInt(cbxAñoNacimiento.getSelectedItem().toString());
        double estatura = Double.parseDouble(txtEstaturaCliente.getText().trim());
        String tipo = cbxTipoCliente.getSelectedItem().toString();
        
        Huesped nuevo = Hotel.crearHuesped(documento, nombre, correo, telefono,
                dia, mes, anio, estatura, tipo);
        if (nuevo != null) {
            JOptionPane.showMessageDialog(this, "Huésped creado correctamente");
            limpiarCamposHuesped();
        } else {
            JOptionPane.showMessageDialog(this, "Ya existe un huésped con este documento");
        }
    }
}

private void buscarHuesped() {
    String doc = txtDocumentoCliente.getText();
    if (doc.isBlank()) {
        JOptionPane.showMessageDialog(this, "Escribe un documento para buscar");
        return;
    }  
    Huesped encontrado = Hotel.buscarHuesped(doc);
    if (encontrado != null) {
        txtNombreCliente.setText(encontrado.getNombre());
        txtCorreoCliente.setText(encontrado.getCorreo());
        txtTelefonoCliente.setText(encontrado.getTelefono());
        txtEstaturaCliente.setText(String.valueOf(encontrado.getEstatura()));
        cbxTipoCliente.setSelectedItem(encontrado.getTipoHuesped());        
        cbxDiaNacimientoCliente.setSelectedItem(String.valueOf(encontrado.getFechaNacimiento().getDayOfMonth()));
        cbxMesNacimientoCliente.setSelectedItem(String.valueOf(encontrado.getFechaNacimiento().getMonthValue()));
        cbxAñoNacimiento.setSelectedItem(String.valueOf(encontrado.getFechaNacimiento().getYear()));
        
        JOptionPane.showMessageDialog(this, "Huésped encontrado");
    } else {
        JOptionPane.showMessageDialog(this, "Huésped NO encontrado");
        limpiarCamposHuesped();
    }
}

private void EliminarHuesped() {
    String doc = txtDocumentoCliente.getText().trim();

    if (doc.isBlank()) {
        JOptionPane.showMessageDialog(this, "Escribe el documento para eliminar");
        return;
    }
    int confirmacion = JOptionPane.showConfirmDialog(this, 
        "¿Seguro que quieres eliminar este huésped?", 
        "Confirmar eliminación", 
        JOptionPane.YES_NO_OPTION);
    if (confirmacion == JOptionPane.YES_OPTION) {
        if (Hotel.eliminarHuesped(doc)) {
            JOptionPane.showMessageDialog(this, "Huésped eliminado");
            limpiarCamposHuesped();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar");
        }
    }
}



private void crearHabitacion() {
    int numero = Integer.parseInt(txtNumeroH.getText().trim());
    String estado = "";
    if (chbDispo.isSelected()) {
        estado = "Disponible";
        chbOcu.setSelected(false);
    }
    if (chbOcu.isSelected()) {
        estado = "Ocupado";
        chbDispo.setSelected(false);
    }
    
    String tipo = jcbTipoHabitacion.getSelectedItem().toString();
    HabitacionSimple nueva = null;
    if (tipo.equalsIgnoreCase("Habitación Sencilla")) { // <-- AQUÍ EL CAMBIO
        nueva = new HabitacionSimple(numero, estado);
}   else if (tipo.equalsIgnoreCase("Habitación Doble")) { // <-- AQUÍ EL CAMBIO
        nueva = new HabitacionDoble(numero, estado);
}   else if (tipo.equalsIgnoreCase("Suite")) { // <-- ESTE QUEDA IGUAL
    nueva = new Suite(numero, estado);
}   else {
    JOptionPane.showMessageDialog(this, "Tipo incorrecto");
    return;
}
    if (Hotel.agregarHabitacion(nueva)) {
        JOptionPane.showMessageDialog(this, "Habitación registrada");
        limpiarCamposHabitacion();
    } else {
        JOptionPane.showMessageDialog(this, "Ya existe ese número de habitación");
    }
}

private void buscarHabitacion() {
    int numero = Integer.parseInt(txtNumeroH.getText().trim());
    HabitacionSimple hab = Hotel.buscarHabitacion(numero);

    if (hab != null) {
        if (hab.getEstado().equals("Disponible")) {
            chbDispo.setSelected(true);
            chbOcu.setSelected(false);
        }
        if (hab.getEstado().equals("Ocupado")) {
            chbOcu.setSelected(true);
            chbDispo.setSelected(false);
        }
        if (hab instanceof HabitacionDoble) {
            jcbTipoHabitacion.setSelectedItem("Habitación Doble");
        } else if (hab instanceof Suite) {
            jcbTipoHabitacion.setSelectedItem("Suite"); // Este quedó igual
        } else {
            jcbTipoHabitacion.setSelectedItem("Habitación Sencilla");
        }
        JOptionPane.showMessageDialog(this, "Habitación encontrada");
    } else {
        JOptionPane.showMessageDialog(this, "Habitación no encontrada");
        limpiarCamposHabitacion();
    }
}

private void eliminarHabitacion() {
    int numero = Integer.parseInt(txtNumeroH.getText().trim());

    int confirmacion = JOptionPane.showConfirmDialog(this, 
        "¿Seguro que quieres eliminar esta habitación?", 
        "Confirmar eliminación", 
        JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        if (Hotel.eliminarHabitacion(numero)) {
            JOptionPane.showMessageDialog(this, "Habitación eliminada");
            limpiarCamposHabitacion();
        } else {
            JOptionPane.showMessageDialog(this, "No existe o no se pudo eliminar");
        }
    }
}

private void actualizarHabitacion() {
    int numero = Integer.parseInt(txtNumeroH.getText().trim());
    String estado = "";
    if (chbDispo.isSelected()) {
        estado = "Disponible";
        chbOcu.setSelected(false);
    }
    if (chbOcu.isSelected()) {
        estado = "Ocupado";
        chbDispo.setSelected(false);
    }

    String tipo = jcbTipoHabitacion.getSelectedItem().toString();

    HabitacionSimple habModificada = null;
      if (tipo.equalsIgnoreCase("Habitación Sencilla")) {
        habModificada = new HabitacionSimple(numero, estado);
    } else if (tipo.equalsIgnoreCase("Habitación Doble")) {
        habModificada = new HabitacionDoble(numero, estado);
    } else if (tipo.equalsIgnoreCase("Suite")) {
        habModificada = new Suite(numero, estado);
    } else {
        JOptionPane.showMessageDialog(this, "Tipo incorrecto");
        return;
    }
    if (Hotel.actualizarHabitacion(habModificada)) {
        JOptionPane.showMessageDialog(this, "Habitación actualizada correctamente");
        limpiarCamposHabitacion();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo actualizar (Número no existe)");
    }
}

private void limpiarCamposHabitacion() {
    txtNumeroH.setText("");
    chbDispo.setSelected(false);
    chbOcu.setSelected(false);
    jcbTipoHabitacion.setSelectedIndex(0);
}



private void crearReserva() {
    try {
        String codigo = txtCodigoRe.getText().trim();
        String documentoHuesped = txtDoc.getText().trim();
        int numeroHabitacion = Integer.parseInt(txtNHabitacion.getText().trim());
        int diaIngreso = Integer.parseInt(jcbDiaIngreso.getSelectedItem().toString().trim());
        int mesIngreso = Integer.parseInt(jcbMesIngreso.getSelectedItem().toString().trim());
        int anioIngreso = Integer.parseInt(jcbAñoIngreso.getSelectedItem().toString().trim());
        LocalDate fechaIngreso = LocalDate.of(anioIngreso, mesIngreso, diaIngreso);
        int diaSalida = Integer.parseInt(jcbDiaSalida.getSelectedItem().toString().trim());
        int mesSalida = Integer.parseInt(jcbMesSalida.getSelectedItem().toString().trim());
        int anioSalida = Integer.parseInt(jcbAñoSalida.getSelectedItem().toString().trim());
        LocalDate fechaSalida = LocalDate.of(anioSalida, mesSalida, diaSalida);

        int cantidadNoches = Integer.parseInt(txtCantidadNoches.getText().trim());
        String tipo = jcbTHabitacion.getSelectedItem().toString();
        double valorPorNoche = 0;
        if (tipo.equals("Suite")) {
            valorPorNoche = 650000;
        } else if (tipo.equals("Habitación Doble")) {
            valorPorNoche = 320000;
        } else if (tipo.equals("Habitación Sencilla")) {
            valorPorNoche = 120000;
        }
        double valorTotal = valorPorNoche * cantidadNoches;
        txtValorTotal.setText(String.valueOf(valorTotal));

        Huesped huespedEncontrado = Hotel.buscarHuesped(documentoHuesped);
        HabitacionSimple habitacionEncontrada = Hotel.buscarHabitacion(numeroHabitacion);

        if (huespedEncontrado == null) {
            JOptionPane.showMessageDialog(this, "El huésped NO existe");
            return;
        }
        if (habitacionEncontrada == null) {
            JOptionPane.showMessageDialog(this, "La habitación NO existe");
            return;
        }
        if (Hotel.crearReserva(codigo, huespedEncontrado, habitacionEncontrada, fechaIngreso, fechaSalida, cantidadNoches, valorPorNoche, valorTotal)) {
            JOptionPane.showMessageDialog(this, "Reserva registrada correctamente");
            limpiarCamposReserva();
        } else {
            JOptionPane.showMessageDialog(this, "Ya existe ese código de reserva");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Revisa los números: N° Habitación, Noches o Valor");
    } catch (Exception e) {
    }
}

private void buscarReserva() {
    String codigo = txtCodigoRe.getText().trim();
    if (codigo.isBlank()) {
        JOptionPane.showMessageDialog(this, "Escribe el código de la reserva para buscar");
        return;
    }

    Reserva encontrada = Hotel.buscarReserva(codigo);
    if (encontrada != null) {
        txtDoc.setText(encontrada.getHuesped().getDocumento());
        txtNHabitacion.setText(String.valueOf(encontrada.getHabitacion().getNumero()));
        txtCantidadNoches.setText(String.valueOf(encontrada.getCantidadNoches()));
        txtValorTotal.setText(String.valueOf(encontrada.getValorTotal()));
        jcbDiaIngreso.setSelectedItem(String.valueOf(encontrada.getFechaIngreso().getDayOfMonth()));
        jcbMesIngreso.setSelectedItem(String.valueOf(encontrada.getFechaIngreso().getMonthValue()));
        jcbAñoIngreso.setSelectedItem(String.valueOf(encontrada.getFechaIngreso().getYear()));
        jcbDiaSalida.setSelectedItem(String.valueOf(encontrada.getFechaSalida().getDayOfMonth()));
        jcbMesSalida.setSelectedItem(String.valueOf(encontrada.getFechaSalida().getMonthValue()));
        jcbAñoSalida.setSelectedItem(String.valueOf(encontrada.getFechaSalida().getYear()));

        JOptionPane.showMessageDialog(this, "Reserva encontrada");
    } else {
        JOptionPane.showMessageDialog(this, "Reserva no encontrada");
        limpiarCamposReserva();
    }
}

private void eliminarReserva() {
    String codigo = txtCodigoRe.getText().trim();
    if (codigo.isBlank()) {
        JOptionPane.showMessageDialog(this, "Escribe el código para eliminar");
        return;
    }
    int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Seguro que quieres eliminar esta reserva?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);
    if (confirmacion == JOptionPane.YES_OPTION) {
        if (Hotel.eliminarReserva(codigo)) {
            JOptionPane.showMessageDialog(this, "Reserva eliminada correctamente");
            limpiarCamposReserva();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar");
        }
    }
}

private void limpiarCamposReserva() {
    txtCodigoRe.setText("");
    txtDoc.setText("");
    txtNHabitacion.setText("");
    txtCantidadNoches.setText("");
    txtValorTotal.setText("");
    jcbDiaIngreso.setSelectedIndex(0);
    jcbMesIngreso.setSelectedIndex(0);
    jcbAñoIngreso.setSelectedIndex(0);
    jcbDiaSalida.setSelectedIndex(0);
    jcbMesSalida.setSelectedIndex(0);
    jcbAñoSalida.setSelectedIndex(0);
}

private void calcularTotal() {
    try {
        int cantidadNoches = Integer.parseInt(txtCantidadNoches.getText().trim());
        String tipo = jcbTHabitacion.getSelectedItem().toString();
        double valorPorNoche;
        if (tipo.equals("Suite")) {
            valorPorNoche = 650000;
        } else if (tipo.equals("Habitación Doble")) {
            valorPorNoche = 320000;
        } else if (tipo.equals("Habitación Sencilla")) {
            valorPorNoche = 120000;
        } else {
            valorPorNoche = 0;
        }
        double total = valorPorNoche * cantidadNoches;
        txtValorTotal.setText(String.valueOf(total));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Ingrese una cantidad de noches válida");
    }
}

}